### ISSUE TITLE
IoA boat disappears?

### ISSUE THREAD

**Issue by default-kramer** [default-kramer/HermitsHeresy#8]
Reported via Discord: "okay so I set the island up with HH.  Filled out the map.  Went into Multiplayer and together we excavated a cave with the ship intact.  I exited multiplayer properly, restarted the game.  Then went to check on the cave to see what we did and no ship."

I used the same hill on my IoA and cannot reproduce. I wonder if Multiplayer has something to do with it?

It's not a silly mistake like not knowing the boat's Block ID; the boat uses 2047 and that ID has definitely been protected since the first release. (Also, the storage sack also uses 2047 and it was preserved just fine.)

They may also have been using the cheat engine at the time, which probably isn't relevant but who knows...

**Comment by Sapphire645** [comment]
I'd ask for the STGDAT file to check the data there (if you can't replicate it)

**Comment by default-kramer** [comment]
Most likely caused by https://github.com/default-kramer/HermitsHeresy/issues/11

**Comment by default-kramer** [comment]
Almost certainly fixed with https://github.com/default-kramer/HermitsHeresy/issues/11

The likely reason I wasn't able to reproduce it is because on my IoA the boat was not submerged.
